/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lv.brain.gradle.xmlbeans;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'lv.brain.gradle.xmlbeans.greeting' plugin.
 */
class XmlbeansPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("lv.brain.gradle.xmlbeans");

        // Verify the result
        assertNotNull(project.getTasks().findByName("generate-source"));
    }
}
